name: power-generation-cycles
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib>=3.5
  - scipy
  - ipywidgets=7.6
  - ipympl=0.8
  - notebook
  - jupyterlab=3
  - nodejs
